# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20170531_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='added_on',
            field=models.DateTimeField(),
        ),
    ]
