# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20170531_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
