# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20170531_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='topic',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Topic'),
        ),
    ]
