# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 11:50
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20170601_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
