# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 18:33
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_auto_20170601_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='method',
            field=models.CharField(choices=[('book', 'Book'), ('ebook', 'eBook'), ('video', 'Video'), ('website', 'Website'), ('blog', 'Blog'), ('mooc', 'MOOC'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True),
        ),
    ]
