# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_auto_20170602_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Resource'),
        ),
    ]
