# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_auto_20170602_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='added_on',
        ),
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(default='/profile_picture/profile_default.jpeg', upload_to='profile_picture'),
        ),
    ]
