# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_auto_20170610_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(default='/profile_picture/default_profile_picture.png', upload_to='profile_picture/'),
        ),
    ]
