# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_auto_20170610_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Person')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Resource')),
            ],
        ),
    ]
