# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0016_auto_20171128_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='categories'),
        ),
    ]
