# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0018_auto_20171128_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Category'),
        ),
    ]
