# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0019_topic_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('pages', models.PositiveIntegerField()),
                ('isbn10', models.PositiveIntegerField()),
                ('isbn13', models.PositiveIntegerField()),
                ('asin', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.AddField(
            model_name='resource',
            name='language',
            field=models.CharField(default='English', max_length=30),
        ),
    ]
