# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0020_auto_20171128_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learn.Category'),
        ),
    ]
