# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-02 07:18
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0023_topic_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, null=True, populate_from='title', unique=True),
        ),
    ]
