# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-02 07:19
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0024_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='title', unique=True),
        ),
    ]
