# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-09 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0026_auto_20171202_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='downvote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='upvote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
