# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-09 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0027_auto_20171209_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='upvote',
        ),
        migrations.AddField(
            model_name='vote',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Resource'),
        ),
    ]
