# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-17 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0031_auto_20181207_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='person',
            field=models.ForeignKey(on_delete=models.SET('Anonymous'), to='learn.Person'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='person',
            field=models.ForeignKey(on_delete=models.SET('Anonymous'), to='learn.Person'),
        ),
        migrations.AlterField(
            model_name='review',
            name='person',
            field=models.ForeignKey(on_delete=models.SET('Anonymous'), to='learn.Person'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='person',
            field=models.ForeignKey(on_delete=models.SET('Anonymous'), to='learn.Person'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='person',
            field=models.ForeignKey(on_delete=models.SET('Anonymous'), to='learn.Person'),
        ),
    ]
