# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-27 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0032_auto_20181217_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('thumbnail_url', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=10)),
                ('view_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('dislike_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
            ],
        ),
    ]
