# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-27 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0034_auto_20181227_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuberesource',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
